#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using Editor.Helpers;
using Unity.VisualScripting;
using UnityEditor;
using UnityEngine;
using Utils;

namespace Editor
{
    public class PrefabPlacer : EditorWindow
    {
        private void Place()
        {
            while (_parent.transform.childCount > 0) DestroyImmediate(_parent.transform.GetChild(0).gameObject);

            var list = JsonUtils.DeserializeFile<List<PrefabWrapper>>(_prefabJsonPath);

            foreach (var wrapper in list) PlacePrefabs(wrapper.Path, wrapper.Coordinates);
        }


        #region Helper

        private void PlacePrefabs(string prefabPath, PrefabLocation[] coords)
        {
            var prefab = Resources.Load<GameObject>(prefabPath);

            if (prefab == null) throw new NullReferenceException("Prefab " + prefabPath + " not found");

            var prefabGroup = new GameObject(prefab.name);

            prefabGroup.transform.SetParent(_parent.transform);

            foreach (var coord in coords)
            {
                var child = PrefabUtility.InstantiatePrefab(prefab, prefabGroup.transform).GameObject();
                child.transform.localPosition = new Vector3(coord.X, coord.Y, coord.Z);
                child.transform.localRotation =
                    new Quaternion(coord.QuarterX, coord.QuarterY, coord.QuarterZ, coord.QuarterW);
                child.transform.localScale = ScaleAbs(child.transform.localScale, coord.Scale);
            }
        }

        private static Vector3 ScaleAbs(Vector3 origin, float factor)
        {
            var newX = Math.Abs(origin.x * factor);
            var newY = Math.Abs(origin.y * factor);
            var newZ = Math.Abs(origin.z * factor);

            return new Vector3(newX, newY, newZ);
        }

        #endregion

        #region Variables

        private GameObject _parent;

        private string _prefabJsonPath;

        #endregion

        #region GUI Setup

        private const string Title = "Place Prefabs";

        [MenuItem(EditorConstants.EditorPath + "/" + Title)]
        public static void ShowWindow()
        {
            GetWindow<PrefabPlacer>(Title);
        }

        private void OnGUI()
        {
            EditorGUILayout.LabelField("Prefab Settings", EditorStyles.boldLabel);
            EditorGUILayout.LabelField("Parent where the prefabs will be placed");
            _parent = (GameObject)EditorGUILayout.ObjectField("Parent", _parent, typeof(GameObject), true);
            EditorGUILayout.Space();

            EditorGUILayout.LabelField("The json file generated by the shmd extractor");
            _prefabJsonPath = EditorGUILayout.TextField("Prefab Json", _prefabJsonPath);

            if (GUILayout.Button("Place prefabs"))
            {
                if (_parent == null)
                {
                    Debug.LogError("Assign parent");
                    return;
                }

                if (_prefabJsonPath == null)
                {
                    Debug.LogError("Assign prefab json");
                    return;
                }

                EditorUtility.DisplayProgressBar("Placing prefabs", "Placing prefabs...", 0.5f);
                Place();
                EditorUtility.ClearProgressBar();
                EditorUtility.DisplayDialog("Done", "Placing has completed", "Ok");
            }
        }

        #endregion
    }
}

#endif